### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by yellowj48**
Added documentation

### CODE REVIEW

**Comment by Dylanjamaludin** [comment]
Aproved

**Comment by yellowj48** [comment]
Do you see it in main branch?

**Comment by Dylanjamaludin** [comment]
No, I think saaketh needs to approve this.

**Comment by Dylanjamaludin** [comment]
Reopened!

**Review by Dylanjamaludin — APPROVED** [review]
Looks good to me!

**Pull request merged**
